HIGHRISE_API_TOKEN: 'Highrise API token'
HIGHRISE_URL: 'https://account.highrisehq.com'
CAMPAIGN_MONITOR_CLIENT_ID: 'Client ID of the Skateistan Online Application Webhook App'
CAMPAIGN_MONITOR_CLIENT_SECRET: 'Client Secret of the Skateistan Online Application Webhook App'
CAMPAIGN_MONITOR_ACCESS_TOKEN: 'Access token for accessing Skateistan Campaign Monitor account'
CAMPAIGN_MONITOR_REFRESH_TOKEN: 'Refresh token for accessing Skateistan Campaign Monitor account'
CAMPAIGN_MONITOR_LIST_ID: 'Campaign Monitor List ID'